---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/10/16 8:20 PM
---

socket = require("socket")

function sleep(sec)
    socket.select(nil, nil, sec)

    return coroutine.yield(sec)
end

corTest = coroutine.create(function()
    print("Start")
    local ret = sleep(5)
    print("End")
end)

corTest2 = coroutine.create(
        function()
            print("Start")
            local ret = sleep(5)
            print("End")
        end
)

print("Start")
sleep(5)
print("End")

coroutine.resume(corTest)
coroutine.resume(corTest2)
--coroutine.resume(corTest)