---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/10/25 2:06 PM
---


--function printStarPlus(nRow)
--    for row = 1, nRow, 1 do
--
--        count = row
--        szStr = ""
--        for column = 1, count, 1 do
--            szStr = szStr .. "*"
--        end
--        print(szStr)
--    end
--end

function printStar2(nRow)
    for row = 1, nRow, 1 do

        szStr = ""
        for column = 1, nRow - row + 1, 1 do
            szStr = szStr .. "*"
        end
        print(szStr)
    end
end

printStar2(5)